### ISSUE TITLE
npm install fails on zmq

### ISSUE THREAD

**Issue by 1am** [0rpc/zerorpc-node#36]
Hello,

I've tried to install zerorpc for both python and node.js. The first one installed without problems (just a few compilation warnings) but node.js fails on zmq package with the following error I've pasted on the end of my post.

This seems like an issue with zmq 2.7.0 package and not npm or zero-rpc but my question is that if there is a way to force using a different version of zmq which will work with zerorpc npm package?

```
Package libzmq was not found in the pkg-config search path.
Perhaps you should add the directory containing `libzmq.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libzmq' found
gyp: Call to 'pkg-config libzmq --libs' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Darwin 13.2.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/zerorpc/node_modules/zmq
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok 
npm ERR! zmq@2.7.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zmq@2.7.0 install script.
npm ERR! This is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.2.0
npm ERR! command "node" "/usr/local/bin/npm" "-g" "install" "zerorpc"
npm ERR! cwd /Users/pb/Documents/tmp
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.5.0-alpha-1
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/pb/Documents/tmp/npm-debug.log
npm ERR! not ok code 0
```

**Comment by AlmoGSIntel** [comment]
I still can't find a solution to this problem, mine looks the same.
In my problem when I do `npm install --save zerorpc` even if I installed zeromq before the install of the zero rpc try to build its own zeromq module for it own node_module folder and failed.
