### ISSUE TITLE
Streaming responses example error

### ISSUE THREAD

**Issue by 1am** [0rpc/zerorpc-node#37]
Hi,

I've been testing streaming responses example from http://zerorpc.dotcloud.com/ website and there seems to be a small problem when i set node.js as server and python as client. Oposite configuration works correctly. I've tried using different ports, etc. but nothing seems to solve the issue. Node server is started first and later I launch the client script.
Does somebody know what could solve the problem?

Python client response:

```
# python client.py 
Traceback (most recent call last):
  File "client.py", line 6, in <module>
    for item in c.streaming_range(10, 20, 2):
  File "/Library/Python/2.7/site-packages/zerorpc/core.py", line 260, in <lambda>
    return lambda *args, **kargs: self(method, *args, **kargs)
  File "/Library/Python/2.7/site-packages/zerorpc/core.py", line 245, in __call__
    return self._process_response(request_event, bufchan, timeout)
  File "/Library/Python/2.7/site-packages/zerorpc/core.py", line 220, in _process_response
    reply_event, self._handle_remote_error)
  File "/Library/Python/2.7/site-packages/zerorpc/patterns.py", line 44, in process_answer
    raise exception
zerorpc.exceptions.RemoteError: Error: None
```

Node.js server response (after I run python client):

```
# node server.js 

/usr/local/lib/node_modules/zerorpc/lib/channel.js:164
        throw new Error("Cannot send on closed channel");
              ^
Error: Cannot send on closed channel
    at ServerChannel.Channel.send (/usr/local/lib/node_modules/zerorpc/lib/channel.js:164:15)
    at sendError (/usr/local/lib/node_modules/zerorpc/lib/server.js:125:12)
    at Server._recv (/usr/local/lib/node_modules/zerorpc/lib/server.js:180:9)
    at MultiplexingSocket.<anonymous> (/usr/local/lib/node_modules/zerorpc/lib/server.js:86:46)
    at MultiplexingSocket.emit (events.js:95:17)
    at MultiplexingSocket.<anonymous> (/usr/local/lib/node_modules/zerorpc/lib/socket.js:106:18)
    at MultiplexingSocket.emit (events.js:95:17)
    at null.<anonymous> (/usr/local/lib/node_modules/zerorpc/lib/socket.js:61:14)
    at emit (events.js:106:17)
    at /usr/local/lib/node_modules/zerorpc/node_modules/zmq/lib/index.js:473:27
```

**Comment by penzrgb** [comment]
I am also experiencing the same issue, running node.js as the server seems to timeout the request even though the message comes through.
