### ISSUE TITLE
Issue when running node app 

### ISSUE THREAD

**Issue by mrlarssen** [0rpc/zerorpc-node#82]
Im getting an issue when running my node app in a docker container. I assume it has something to do with the latest version of node, as I have been using this library successfully for about 6 months now.

I tried with node 6, but that gave me the same error. Happens when launching my node.js app.

Any ideas?
```
/code/node_modules/bindings/bindings.js:91
node        |   throw err
node        |   ^
node        | 
node        | Error: Could not locate the bindings file. Tried:
node        |  → /code/node_modules/zmq/build/zmq.node
node        |  → /code/node_modules/zmq/build/Debug/zmq.node
node        |  → /code/node_modules/zmq/build/Release/zmq.node
node        |  → /code/node_modules/zmq/out/Debug/zmq.node
node        |  → /code/node_modules/zmq/Debug/zmq.node
node        |  → /code/node_modules/zmq/out/Release/zmq.node
node        |  → /code/node_modules/zmq/Release/zmq.node
node        |  → /code/node_modules/zmq/build/default/zmq.node
node        |  → /code/node_modules/zmq/compiled/6.4.0/linux/x64/zmq.node
node        |     at bindings (/code/node_modules/bindings/bindings.js:88:9)
node        |     at Object.<anonymous> (/code/node_modules/zmq/lib/index.js:6:30)
node        |     at Module._compile (module.js:556:32)
node        |     at Module._extensions..js (module.js:565:10)
node        |     at Object.require.extensions.(anonymous function) [as .js] (/code/node_modules/babel-register/lib/node.js:152:7)
node        |     at Module.load (module.js:473:32)
node        |     at tryModuleLoad (module.js:432:12)
node        |     at Function.Module._load (module.js:424:3)
node        |     at Module.require (module.js:483:17)
node        |     at require (internal/module.js:20:19)
```

**Comment by mrlarssen** [comment]
npm rebuild solved it
