### ISSUE TITLE
Installing issue

### ISSUE THREAD

**Issue by pwichmann** [0rpc/zerorpc-node#83]
I have spent about 6 hours trying to get zerorpc installed but I cannot get past the following error message:

```
root@lem-nodejs-512mb:/var/www/lem_nodejs/nodejs# npm install zerorpc

> zmq@2.15.3 install /var/www/lem_nodejs/nodejs/node_modules/zmq
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/var/www/lem_nodejs/nodejs/node_modules/zmq/build'
  CXX(target) Release/obj.target/zmq/binding.o
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
zmq.target.mk:94: recipe for target 'Release/obj.target/zmq/binding.o' failed
make: *** [Release/obj.target/zmq/binding.o] Error 4
make: Leaving directory '/var/www/lem_nodejs/nodejs/node_modules/zmq/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v6.9.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-59-generic
gyp ERR! command "/root/.nvm/versions/node/v6.9.2/bin/node" "/root/.nvm/versions/node/v6.9.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/lem_nodejs/nodejs/node_modules/zmq
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN lem@0.0.1 No repository field.
npm ERR! Linux 4.4.0-59-generic
npm ERR! argv "/root/.nvm/versions/node/v6.9.2/bin/node" "/root/.nvm/versions/node/v6.9.2/bin/npm" "install" "zerorpc"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.15.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zmq@2.15.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zmq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/lem_nodejs/nodejs/npm-debug.log
```
Any ideas what I am doing wrong?
System:
* Node: v6.9.2
* Ubuntu: LTS 16.04

EDIT: I updated this issue for improved clarity.

**Comment by bombela** [comment]
Apparently, gcc is crashing and asks you to send a full bug report to the gcc developers.

What is the output of `g++ --version` on your system?

**Comment by pwichmann** [comment]
Thanks for replying, bombela.

The output is:
```
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
```

**Comment by bombela** [comment]
I have `g++ (Ubuntu 6.2.0-5ubuntu12) 6.2.0 20161005` and I just rebuilt zerorpc-node without trouble (Ubuntu 16.10).

Maybe its a matters of updating/reinstalling gcc?

**Comment by pwichmann** [comment]
Thank you.
I have no idea what I am doing wrong.

**Comment by pwichmann** [comment]
I found the problem.
You were right. It was a matter of updating gcc to version 6.

This script here helped:
https://gist.github.com/application2000/73fd6f4bf1be6600a2cf9f56315a2d91

I am sorry for the trouble. And many thanks to you for your help and work!

**Comment by bombela** [comment]
Interesting, thank you for reporting your results!
